### ISSUE TITLE
不建议使用raliway部署

### ISSUE THREAD

**Issue by VOfficial404** [k0baya/xiaoya_alist_docker_on_render#1]
raliway免费版每月限制500h，绑卡以后不限制时间但是按使用量来计价（每月免费5.0刀）

**Comment by saika2077** [comment]
Railway无法部署小雅的Docker镜像，因为Railway只能监听0.0.0.0:PORT，而小雅是127.0.0.1，此仓库无法在Railway正常使用。请使用Render。

**Comment by k0baya** [comment]
> 

你说的很对，Railway无法部署，此仓库也没有提到用Railway部署小雅。
