### ISSUE TITLE
CodeSandBox怎么让所有人都能访问

### ISSUE THREAD

**Issue by shaping520** [k0baya/xiaoya_alist_docker_on_render#10]
作者你好，CodeSandBox我看了下免费的只有400积分，不能做到真正的免费啊，而且只能自己登录后在他们网站内访问吧，怎么让所有人都能访问呢？谢谢

**Comment by k0baya** [comment]
你可以在置顶的issue里看到一个叫做cloudflare argo tunnel的东西，启动cf隧道打洞就可以正常访问。另外在那个issue里我也已经提了不用csb了，现在每个月只有40小时免费，请另寻平台或者干脆网络扫描使用，因为小雅的alist特征明显且多数人直接部署在公网而不加密，已经没有多大必要自行部署。
