### ISSUE TITLE
倒数第二步没有太看懂

### ISSUE THREAD

**Issue by asicer416** [k0baya/xiaoya_alist_docker_on_render#2]
我已经可以成功打开网页了，但是里面的资源我下载不了也看不了，导入到我自己的alist也失败了

**Comment by asicer416** [comment]
装载到自己的时候 “Failed init storage: the site does not allow mounted”

**Comment by k0baya** [comment]
首先，你直接打开看看不了，有可能是你的三个必要参数没有填对。
然后，如果无法装载，请首先检查你自己的Alist的IP地址是否能与`*.onrender.com`正常通信。假如你的Alist是利用Replit之类的平台部署的，很大概率上你的Alist的IP地址已经被Render禁止访问了。

**Comment by asicer416** [comment]
你好，我重新按步骤部署了一次，我的render运行之后log窗口显示成功但是没有像你倒数第二张图片的提示。
我的Alist是用的本地地址。
现在还是像之前那样进得去网站但是播放下载不了
部署还是提示“: wsarecv: An existing connection was forcibly closed by the remote host.”

**Comment by asicer416** [comment]
你好，我重新按步骤部署了一次，我的render运行之后log窗口显示成功但是没有像你倒数第二张图片的提示。
我的Alist是用的本地地址。
现在还是像之前那样进得去网站但是播放下载不了
部署还是提示“: wsarecv: An existing connection was forcibly closed by the remote host.”

**Comment by k0baya** [comment]
> 你好，我重新按步骤部署了一次，我的render运行之后log窗口显示成功但是没有像你倒数第二张图片的提示。 我的Alist是用的本地地址。 现在还是像之前那样进得去网站但是播放下载不了 部署还是提示“: wsarecv: An existing connection was forcibly closed by the remote host.”

首先请确保自己的三个必要参数都填写正确了。不然无法出现本仓库README.md当中一样的log。然后Render的服务器区域有几个选项可以选择，有些区域似乎无法正确部署小雅，具体我没有统计，请自行尝试。
