### ISSUE TITLE
网站打不开

### ISSUE THREAD

**Issue by wobuhui666** [k0baya/xiaoya_alist_docker_on_render#6]
![BBAD892E-16B9-4466-B859-0C8540B6E89F](https://github.com/k0baya/xiaoya_alist_docker_on_render/assets/121330915/7b44321c-fcc4-42ca-abdc-f5e9cb850f4c)
logs里面已经显示这个了，但是网站打不开
![9885CEFE-03CC-4B19-9ACC-1E2C6665DEED](https://github.com/k0baya/xiaoya_alist_docker_on_render/assets/121330915/46af98fc-671c-4e14-acec-ba15ec286281)

**Comment by wobuhui666** [comment]
重新部署了一下变404了

**Comment by chotamaki** [comment]
我的也是，好不容易部署成功，页面打不开，什么也看不了

**Comment by wwlww** [comment]
四个区域都试了，不行

**Comment by ghost** [comment]
也是打不开，还把帐号给ban了 😭

**Comment by k0baya** [comment]
请更换其他平台部署。
