### ISSUE TITLE
sandbox 小雅相关问题

### ISSUE THREAD

**Issue by cyclestudy** [k0baya/xiaoya_alist_docker_on_render#9]
<img width="647" alt="image" src="https://github.com/k0baya/xiaoya_alist_docker_on_render/assets/115349959/3db5391f-8e96-4f6c-88d6-aa7acabbddbd">
大佬这个怎么解决？在 sandbox 上，相应的文件都有读取不到吗？

**Comment by k0baya** [comment]
> <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/115349959/292723024-3db5391f-8e96-4f6c-88d6-aa7acabbddbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTM3NTQsIm5iZiI6MTcwMzc1MzQ1NCwicGF0aCI6Ii8xMTUzNDk5NTkvMjkyNzIzMDI0LTNkYjUzOTFmLThlOTYtNGY2Yy04OGQ2LWFhN2FjYWJiZGRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODhlYjAxYTJkNDM0ZjRlNjM4MTdjZTU2NGQxNWViMTU1MjUwZmQwZDY4ZWJiOTZmZmU1ODliNmFjMzMxNTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ng3i8aBaedXM7jZO7KyjaeQ_E9iIlVVtIZH_68QQCbQ"> 大佬这个怎么解决？在 sandbox 上，相应的文件都有读取不到吗？

我在codesandbox上搭了一个临时blog，这篇[文章](https://blog.saika.free.hr/archives/codesandbox_other_apps)有详细说明。

**Comment by benefit77** [comment]
> > <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/115349959/292723024-3db5391f-8e96-4f6c-88d6-aa7acabbddbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTM3NTQsIm5iZiI6MTcwMzc1MzQ1NCwicGF0aCI6Ii8xMTUzNDk5NTkvMjkyNzIzMDI0LTNkYjUzOTFmLThlOTYtNGY2Yy04OGQ2LWFhN2FjYWJiZGRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODhlYjAxYTJkNDM0ZjRlNjM4MTdjZTU2NGQxNWViMTU1MjUwZmQwZDY4ZWJiOTZmZmU1ODliNmFjMzMxNTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ng3i8aBaedXM7jZO7KyjaeQ_E9iIlVVtIZH_68QQCbQ"> 大佬这个怎么解决？在 sandbox 上，相应的文件都有读取不到吗？
> 
> 我在codesandbox上搭了一个临时blog，这篇[文章](https://blog.saika.free.hr/archives/codesandbox_other_apps)有详细说明。

大佬，你这个访问不了了

**Comment by cyclestudy** [comment]
> > <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/115349959/292723024-3db5391f-8e96-4f6c-88d6-aa7acabbddbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTM3NTQsIm5iZiI6MTcwMzc1MzQ1NCwicGF0aCI6Ii8xMTUzNDk5NTkvMjkyNzIzMDI0LTNkYjUzOTFmLThlOTYtNGY2Yy04OGQ2LWFhN2FjYWJiZGRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODhlYjAxYTJkNDM0ZjRlNjM4MTdjZTU2NGQxNWViMTU1MjUwZmQwZDY4ZWJiOTZmZmU1ODliNmFjMzMxNTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ng3i8aBaedXM7jZO7KyjaeQ_E9iIlVVtIZH_68QQCbQ"> 大佬这个怎么解决？在 sandbox 上，相应的文件都有读取不到吗？
> 
> 我在codesandbox上搭了一个临时blog，这篇[文章](https://blog.saika.free.hr/archives/codesandbox_other_apps)有详细说明。

博客挂了

**Comment by darkelf123** [comment]
博客又挂了？

**Comment by k0baya** [comment]
> > > <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/115349959/292723024-3db5391f-8e96-4f6c-88d6-aa7acabbddbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTM3NTQsIm5iZiI6MTcwMzc1MzQ1NCwicGF0aCI6Ii8xMTUzNDk5NTkvMjkyNzIzMDI0LTNkYjUzOTFmLThlOTYtNGY2Yy04OGQ2LWFhN2FjYWJiZGRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODhlYjAxYTJkNDM0ZjRlNjM4MTdjZTU2NGQxNWViMTU1MjUwZmQwZDY4ZWJiOTZmZmU1ODliNmFjMzMxNTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ng3i8aBaedXM7jZO7KyjaeQ_E9iIlVVtIZH_68QQCbQ"> 大佬这个怎么解决？在 sandbox 上，相应的文件都有读取不到吗？
> > 
> > 
> > 我在codesandbox上搭了一个临时blog，这篇[文章](https://blog.saika.free.hr/archives/codesandbox_other_apps)有详细说明。
> 
> 博客挂了

本来就是临时的。。。随时会挂掉，没有长期保留的打算。。。
另外，现在https://hax.co.id/ 的US2区域已经可以直接使用docker容器，可以直接用小雅的脚本一键安装小雅，还可以使用Cloudflared隧穿出来，比起csb稳定太多啦。

**Comment by darkelf123** [comment]
> > > > <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/115349959/292723024-3db5391f-8e96-4f6c-88d6-aa7acabbddbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTM3NTQsIm5iZiI6MTcwMzc1MzQ1NCwicGF0aCI6Ii8xMTUzNDk5NTkvMjkyNzIzMDI0LTNkYjUzOTFmLThlOTYtNGY2Yy04OGQ2LWFhN2FjYWJiZGRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODhlYjAxYTJkNDM0ZjRlNjM4MTdjZTU2NGQxNWViMTU1MjUwZmQwZDY4ZWJiOTZmZmU1ODliNmFjMzMxNTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ng3i8aBaedXM7jZO7KyjaeQ_E9iIlVVtIZH_68QQCbQ"> 大佬这个怎么解决？在 sandbox 上，相应的文件都有读取不到吗？
> > > 
> > > 
> > > 我在codesandbox上搭了一个临时blog，这篇[文章](https://blog.saika.free.hr/archives/codesandbox_other_apps)有详细说明。
> > 
> > 
> > 博客挂了
> 
> 本来就是临时的。。。随时会挂掉，没有长期保留的打算。。。 另外，现在https://hax.co.id/ 的US2区域已经可以直接使用docker容器，可以直接用小雅的脚本一键安装小雅，还可以使用Cloudflared隧穿出来，比起csb稳定太多啦。

cloudflared隧穿应该怎么操作？能否指导一下？

**Comment by k0baya** [comment]
> > > > > <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/115349959/292723024-3db5391f-8e96-4f6c-88d6-aa7acabbddbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTM3NTQsIm5iZiI6MTcwMzc1MzQ1NCwicGF0aCI6Ii8xMTUzNDk5NTkvMjkyNzIzMDI0LTNkYjUzOTFmLThlOTYtNGY2Yy04OGQ2LWFhN2FjYWJiZGRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODhlYjAxYTJkNDM0ZjRlNjM4MTdjZTU2NGQxNWViMTU1MjUwZmQwZDY4ZWJiOTZmZmU1ODliNmFjMzMxNTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ng3i8aBaedXM7jZO7KyjaeQ_E9iIlVVtIZH_68QQCbQ"> 大佬这个怎么解决？在 sandbox 上，相应的文件都有读取不到吗？
> > > > 
> > > > 
> > > > 我在codesandbox上搭了一个临时blog，这篇[文章](https://blog.saika.free.hr/archives/codesandbox_other_apps)有详细说明。
> > > 
> > > 
> > > 博客挂了
> > 
> > 
> > 本来就是临时的。。。随时会挂掉，没有长期保留的打算。。。 另外，现在https://hax.co.id/ 的US2区域已经可以直接使用docker容器，可以直接用小雅的脚本一键安装小雅，还可以使用Cloudflared隧穿出来，比起csb稳定太多啦。
> 
> cloudflared隧穿应该怎么操作？能否指导一下？

`./cloudflared tunnel --edge-ip-version auto --protocol http2 --heartbeat-interval 10s run --token ARGO_TOKEN`
当然最好直接上docker，这种简单问题自己查一下或者GPT就行。

**Comment by benefit6** [comment]
> > <img alt="图像" width="647" src="https://private-user-images.githubusercontent.com/115349959/292723024-3db5391f-8e96-4f6c-88d6-aa7acabbddbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTM3NTQsIm5iZiI6MTcwMzc1MzQ1NCwicGF0aCI6Ii8xMTUzNDk5NTkvMjkyNzIzMDI0LTNkYjUzOTFmLThlOTYtNGY2Yy04OGQ2LWFhN2FjYWJiZGRiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODhlYjAxYTJkNDM0ZjRlNjM4MTdjZTU2NGQxNWViMTU1MjUwZmQwZDY4ZWJiOTZmZmU1ODliNmFjMzMxNTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ng3i8aBaedXM7jZO7KyjaeQ_E9iIlVVtIZH_68QQCbQ">大佬这个怎么解决？在沙箱上，相应的文件都有读取不到吗？
> 
> 我在codesandbox上搭了一个临时博客，这篇[文章](https://blog.saika.free.hr/archives/codesandbox_other_apps)有详细说明。

大佬。你能把之前codesandbox上创建xiaoya的命令发出来嘛。
